### ISSUE TITLE
Can you provide pre-training model?

### ISSUE THREAD

**Issue by lunalulu** [narumiruna/mnasnet-pytorch#1]
thanks for your great job!

Can you provide pre-training model with mnasnet-a1?

**Comment by narumiruna** [comment]
No, I don't have pre-trained model with mnasnet-a1.

**Comment by lunalulu** [comment]
👌，thanks for your reply！




| |
BoxrOQ
邮箱：lujing1987317@163.com
|

Signature is customized by Netease Mail Master

On 07/01/2019 17:08, なるみ wrote:

No, I don't have pre-trained model with mnasnet-a1.
